# BoxLocation.py — Professional UI + Simple Workflow + Sticky Header + Tabs (NO DEBUG)
# ============================================================
# ✅ Storage = LN Tank uses tab LN3 ONLY
# ✅ Subset LN3 by TankID == LN1/LN2/LN3 and show LN Inventory Table
# ✅ FIND tab:
#    - Storage=LN Tank: show LN Inventory Table (selected tank)
#    - Storage=Freezer: show Freezer Search by BoxLabel_group (selected freezer)
# ✅ Box Location expander behavior (your new request):
#    - Storage=LN Tank: minimized/collapsed
#    - Storage=Freezer + Freezer=Sammy: maximized/expanded
#    - Storage=Freezer + Freezer=Tom/Jerry: minimized/collapsed
# ✅ Workflow tabs: Find / Add / Use / History / Session Report
# ✅ Compact Context Bar always visible
# ✅ Sticky header (best-effort CSS)
# ✅ ADD tab behavior:
#    - Storage=LN Tank -> Add to LN ONLY (Freezer add hidden)
#    - Storage=Freezer -> Add to Freezer ONLY (LN add hidden)
#    - FreezerID follows Context Freezer (Sammy/Tom/Jerry) and is locked
# ✅ QR is generated by QuickChart (no qrcode dependency)
# ✅ fetch_bytes() disables proxies to reduce SSL WRONG_VERSION_NUMBER issues
# ✅ After saving Freezer record:
#    - INSERT a NEW row into boxNumber tab:
#      * StudyID   = "Prefix + Tube suffix" (from Freezer_Inventory)
#      * BoxNumber = BoxID used in Freezer_Inventory
# ✅ When Freezer TubeAmount becomes 0:
#    - Delete the Freezer_Inventory row
#    - Delete matching boxNumber row(s) where StudyID == "Prefix + Tube suffix"
# ✅ Download CSV file_name includes TubeNumber, Time_stamp, and ShippingTo
# ✅ Mitigate Google Sheets 429 read quota using caching on reads (TTL)
# ✅ Max BoxID rules:
#    - Freezer add: max BoxID comes from boxNumber!BoxNumber
#    - LN add:      max BoxID comes from LN3!BoxID
# ============================================================

import re
import time
import random
import urllib.parse
import urllib.request
from datetime import datetime
from typing import Tuple, List

import pandas as pd
import pytz
import streamlit as st
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# -------------------- Page --------------------
st.set_page_config(
    page_title="Sample Inventory",
    layout="centered",
    initial_sidebar_state="collapsed",
)

# -------------------- Sticky header + clean UI CSS --------------------
st.markdown(
    """
<style>
.block-container { padding-top: 0.75rem; }
[data-testid="stAppViewContainer"] > .main > div:first-child {
  position: sticky;
  top: 0;
  z-index: 999;
  background: rgba(255,255,255,0.92);
  backdrop-filter: blur(8px);
  border-bottom: 1px solid rgba(0,0,0,0.08);
}
h1 { margin: 0.1rem 0 0.25rem 0; }
h2, h3 { margin-top: 0.6rem; }
@media (max-width: 640px) {
  .block-container { padding-left: 0.8rem; padding-right: 0.8rem; padding-top: 0.6rem; }
  h1 { font-size: 1.35rem; }
  h2 { font-size: 1.1rem; }
  h3 { font-size: 1.02rem; }
  .stButton>button, .stDownloadButton>button { width: 100%; }
  .stTextInput>div>div>input,
  .stNumberInput>div>div>input,
  .stSelectbox>div>div,
  .stTextArea textarea { font-size: 1rem; }
}
div[data-testid="stDataFrame"] { padding: 0.25rem 0; }
.stTabs [data-baseweb="tab-list"] { gap: 0.25rem; }
.stTabs [data-baseweb="tab"] { padding: 8px 12px; border-radius: 10px; }
.stTabs [aria-selected="true"] { border-bottom: none !important; background: rgba(0,0,0,0.05); }
</style>
""",
    unsafe_allow_html=True,
)

# -------------------- Session State --------------------
if "last_qr_link" not in st.session_state:
    st.session_state.last_qr_link = ""
if "last_qr_uid" not in st.session_state:
    st.session_state.last_qr_uid = ""
if "usage_final_rows" not in st.session_state:
    st.session_state.usage_final_rows = []
if "mobile_mode" not in st.session_state:
    st.session_state.mobile_mode = True

# -------------------- Constants --------------------
DISPLAY_TABS = ["Cocaine", "Cannabis", "HIV-neg-nondrug", "HIV+nondrug"]
TAB_MAP = {
    "Cocaine": "cocaine",
    "Cannabis": "cannabis",
    "HIV-neg-nondrug": "HIV-neg-nondrug",
    "HIV+nondrug": "HIV+nondrug",
}

BOX_TAB = "boxNumber"
LN_TAB = "LN3"
FREEZER_TAB = "Freezer_Inventory"
USE_LOG_TAB = "Use_log"

BOX_LABEL_COL = "BoxLabel_group"
BOXID_COL = "BoxID"
AMT_COL = "TubeAmount"
MEMO_COL = "Memo"

TANK_COL = "TankID"
RACK_COL = "RackNumber"
TUBE_COL = "TubeNumber"
BOXUID_COL = "BoxUID"
QR_COL = "QRCodeLink"

FREEZER_COL = "FreezerID"
PREFIX_COL = "Prefix"
SUFFIX_COL = "Tube suffix"
DATE_COLLECTED_COL = "Date Collected"
SAMPLES_RECEIVED_COL = "Samples Received"
MISSING_COL = "Missing"
URINE_RESULTS_COL = "Urine Results"
COLLECTED_BY_COL = "Collected By"

HIV_CODE = {"HIV+": "HP", "HIV-": "HN"}
DRUG_CODE = {"Cocaine": "COC", "Cannabis": "CAN", "Poly": "POL", "NON-DRUG": "NON-DRUG"}

QR_PX = 118
SPREADSHEET_ID = st.secrets["connections"]["gsheets"]["spreadsheet"]
NY_TZ = pytz.timezone("America/New_York")

# -------------------- Google Sheets service --------------------
@st.cache_resource(show_spinner=False)
def sheets_service():
    scopes = ["https://www.googleapis.com/auth/spreadsheets"]
    creds = Credentials.from_service_account_info(dict(st.secrets["google_service_account"]), scopes=scopes)
    return build("sheets", "v4", credentials=creds, cache_discovery=False)

# -------------------- Helpers --------------------
def safe_strip(x) -> str:
    return "" if x is None else str(x).strip()

def normalize_spaces(s: str) -> str:
    return re.sub(r"\s+", " ", safe_strip(s))

def to_int_amount(x, default=0) -> int:
    try:
        s = safe_strip(x)
        if s == "":
            return default
        return int(float(s))
    except Exception:
        return default

def col_to_a1(col_idx_0based: int) -> str:
    n = col_idx_0based + 1
    s = ""
    while n:
        n, r = divmod(n - 1, 26)
        s = chr(65 + r) + s
    return s

def now_timestamp_str() -> str:
    now = datetime.now(NY_TZ)
    time_str = now.strftime("%I:%M:%S").lstrip("0") or now.strftime("%I:%M:%S")
    date_str = now.strftime("%m/%d/%Y")
    return f"{time_str} {date_str}"

def today_str_ny() -> str:
    d = datetime.now(NY_TZ).date()
    return d.strftime("%m/%d/%Y")

def split_tube_number(t: str) -> Tuple[str, str]:
    t = normalize_spaces(t)
    if not t:
        return "", ""
    parts = t.split(" ", 1)
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], parts[1]

def qr_link_for_boxuid(box_uid: str, px: int = QR_PX) -> str:
    text = urllib.parse.quote(box_uid, safe="")
    return f"https://quickchart.io/qr?text={text}&size={px}&ecLevel=Q&margin=1"

def fetch_bytes(url: str, timeout: int = 12) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    with opener.open(req, timeout=timeout) as resp:
        return resp.read()

def err_detail(e: Exception) -> str:
    try:
        if isinstance(e, HttpError):
            content = getattr(e, "content", b"")
            if content:
                return content.decode("utf-8", errors="ignore")
    except Exception:
        pass
    return str(e)

def read_tab(tab_name: str) -> pd.DataFrame:
    svc = sheets_service()
    resp = svc.spreadsheets().values().get(
        spreadsheetId=SPREADSHEET_ID,
        range=f"{tab_name}!A1:ZZ",
        valueRenderOption="UNFORMATTED_VALUE",
    ).execute()

    values = resp.get("values", [])
    if not values:
        return pd.DataFrame()

    header_raw = [safe_strip(h) for h in values[0]]
    last = max([i for i, h in enumerate(header_raw) if h != ""], default=-1)
    header = header_raw[: last + 1] if last >= 0 else []
    rows = values[1:]
    n = len(header)

    if n == 0:
        return pd.DataFrame()

    fixed = []
    for r in rows:
        r = list(r)
        if len(r) < n:
            r += [""] * (n - len(r))
        elif len(r) > n:
            r = r[:n]
        fixed.append(r)

    return pd.DataFrame(fixed, columns=header)

def read_tab_with_backoff(tab_name: str, tries: int = 5) -> pd.DataFrame:
    for i in range(tries):
        try:
            return read_tab(tab_name)
        except HttpError as e:
            msg = err_detail(e)
            if "429" in msg or "RESOURCE_EXHAUSTED" in msg or "RATE_LIMIT_EXCEEDED" in msg:
                time.sleep((2 ** i) + random.random())
                continue
            raise
    raise RuntimeError(f"Read quota exceeded too long when reading {tab_name}. Try again in ~1 minute.")

@st.cache_data(ttl=30, show_spinner=False)
def read_tab_cached(tab_name: str) -> pd.DataFrame:
    return read_tab_with_backoff(tab_name)

@st.cache_data(ttl=300, show_spinner=False)
def get_sheet_titles(spreadsheet_id: str) -> list:
    svc = sheets_service()
    meta = svc.spreadsheets().get(spreadsheetId=spreadsheet_id).execute()
    return [s["properties"]["title"] for s in meta.get("sheets", [])]

@st.cache_data(show_spinner=False)
def get_sheet_id_map(spreadsheet_id: str) -> dict:
    svc = sheets_service()
    meta = svc.spreadsheets().get(spreadsheetId=spreadsheet_id).execute()
    return {s["properties"]["title"]: int(s["properties"]["sheetId"]) for s in meta.get("sheets", [])}

def get_sheet_id(service, sheet_title: str) -> int:
    m = get_sheet_id_map(SPREADSHEET_ID)
    if sheet_title in m:
        return m[sheet_title]
    raise ValueError(f"Could not find sheetId for tab: {sheet_title}")

def get_header(service, tab: str) -> list:
    resp = service.spreadsheets().values().get(
        spreadsheetId=SPREADSHEET_ID,
        range=f"{tab}!A1:ZZ1",
        valueRenderOption="UNFORMATTED_VALUE",
    ).execute()
    row1 = (resp.get("values", [[]]) or [[]])[0]
    row1 = [safe_strip(x) for x in row1]
    last = max([i for i, h in enumerate(row1) if h != ""], default=-1)
    return row1[: last + 1] if last >= 0 else []

def set_header_if_blank(service, tab: str, header: list):
    resp = service.spreadsheets().values().get(
        spreadsheetId=SPREADSHEET_ID,
        range=f"{tab}!A1:ZZ1",
        valueRenderOption="UNFORMATTED_VALUE",
    ).execute()
    row1 = (resp.get("values", [[]]) or [[]])[0]
    row1 = [safe_strip(x) for x in row1]
    if (not row1) or all(x == "" for x in row1):
        service.spreadsheets().values().update(
            spreadsheetId=SPREADSHEET_ID,
            range=f"{tab}!A1",
            valueInputOption="RAW",
            body={"values": [header]},
        ).execute()

def append_row_by_header(service, tab: str, data: dict):
    header = get_header(service, tab)
    if not header:
        raise ValueError(f"{tab} header row is empty.")
    aligned = [data.get(col, "") for col in header]
    service.spreadsheets().values().append(
        spreadsheetId=SPREADSHEET_ID,
        range=f"{tab}!A:ZZ",
        valueInputOption="RAW",
        insertDataOption="INSERT_ROWS",
        body={"values": [aligned]},
    ).execute()

def ensure_ln_header(service):
    set_header_if_blank(service, LN_TAB, [
        "TankID", "RackNumber", "BoxLabel_group", "BoxUID",
        "TubeNumber", "TubeAmount", "Memo", "BoxID", "QRCodeLink",
    ])

def ensure_freezer_header(service):
    set_header_if_blank(service, FREEZER_TAB, [
        "FreezerID", "BoxID", "Prefix", "Tube suffix", "TubeAmount",
        "Date Collected", "BoxLabel_group", "Samples Received",
        "Missing", "Urine Results", "Collected By", "Memo",
    ])

def ensure_use_log_header(service):
    set_header_if_blank(service, USE_LOG_TAB, [
        "StorageType", "TankID", "RackNumber", "FreezerID",
        "BoxLabel_group", "BoxID", "TubeNumber", "Prefix", "Tube suffix",
        "Use", "User", "Time_stamp", "ShippingTo", "Memo",
    ])

def ensure_boxnumber_header(service):
    set_header_if_blank(service, BOX_TAB, ["StudyID", "BoxNumber"])

def show_df_view(df: pd.DataFrame, key_cols: list, height_mobile: int = 360, height_desktop: int = 520, key_prefix: str = "df"):
    if df is None or df.empty:
        st.info("No records.")
        return
    show_all = st.checkbox("Show all columns", value=not st.session_state.mobile_mode, key=f"{key_prefix}_show_all")
    if st.session_state.mobile_mode and not show_all:
        cols = [c for c in key_cols if c in df.columns]
        st.dataframe(df[cols] if cols else df, use_container_width=True, hide_index=True, height=height_mobile)
    else:
        st.dataframe(df, use_container_width=True, hide_index=True, height=height_desktop)

def build_box_map() -> dict:
    df = read_tab_cached(BOX_TAB)
    if df.empty:
        return {}
    study_col = "StudyID" if "StudyID" in df.columns else None
    box_col = "BoxNumber" if "BoxNumber" in df.columns else None
    if not study_col or not box_col:
        return {}
    m = {}
    for _, r in df.iterrows():
        sid = safe_strip(r.get(study_col, "")).upper()
        bx = safe_strip(r.get(box_col, ""))
        if sid:
            m[sid] = bx
    return m

# -------------------- Preflight --------------------
service = sheets_service()
try:
    titles = get_sheet_titles(SPREADSHEET_ID)
except Exception as e:
    st.error("❌ Unable to connect to Google Sheets.")
    st.code(err_detail(e), language="text")
    st.stop()

required_tabs = [USE_LOG_TAB, LN_TAB, FREEZER_TAB, BOX_TAB]
study_required = list(TAB_MAP.values())
missing_tabs = [t for t in required_tabs if t not in titles]
missing_study = [t for t in study_required if t not in titles]
if missing_tabs or missing_study:
    st.error("❌ Google Sheet is missing required tabs.")
    if missing_tabs: st.caption(f"Missing required tabs: {missing_tabs}")
    if missing_study: st.caption(f"Missing study tabs: {missing_study}")
    st.stop()

try:
    ensure_use_log_header(service)
    ensure_ln_header(service)
    ensure_freezer_header(service)
    ensure_boxnumber_header(service)
except Exception as e:
    st.error("❌ Sheet preflight failed.")
    st.code(err_detail(e), language="text")
    st.stop()

# ============================================================
# Header
# ============================================================
st.title("📦 Sample Inventory")

c_status, c_toggle = st.columns([1, 1])
with c_status:
    st.success("Connected", icon="✅")
with c_toggle:
    st.session_state.mobile_mode = st.toggle("📱 Mobile", value=st.session_state.mobile_mode)

# -------------------- Context Bar --------------------
ctx1, ctx2, ctx3 = st.columns([1.25, 1, 1])
with ctx1:
    selected_display_tab = st.selectbox("Study", DISPLAY_TABS, index=0, key="ctx_study")
with ctx2:
    STORAGE_TYPE = st.selectbox("Storage", ["LN Tank", "Freezer"], index=0, key="ctx_storage")
with ctx3:
    if STORAGE_TYPE == "LN Tank":
        selected_tank = st.selectbox("Tank", ["LN1", "LN2", "LN3"], index=2, key="ctx_tank")
        selected_freezer = None
    else:
        selected_freezer = st.selectbox("Freezer", ["Sammy", "Tom", "Jerry"], index=0, key="ctx_freezer")
        selected_tank = None

# ============================================================
# Tabs
# ============================================================
tab_find, tab_add, tab_use, tab_history, tab_session = st.tabs(
    ["🔎 Find", "➕ Add", "📉 Use", "🧾 History", "✅ Session Report"]
)

# ============================================================
# FIND
# ============================================================
with tab_find:
    st.subheader("Find / Locate")

    # ✅ Your request:
    # - Freezer=Sammy => Box Location expanded
    # - Freezer=Tom/Jerry => Box Location collapsed (even though title says 📦 SAMMY...)
    if STORAGE_TYPE == "LN Tank":
        boxloc_expanded = False
        boxloc_title = "📦 Box Location"
    else:
        # Always label as 📦 SAMMY: Box Location (your request text)
        boxloc_title = "📦 SAMMY: Box Location"
        boxloc_expanded = (safe_strip(selected_freezer).lower() == "sammy")

    with st.expander(boxloc_title, expanded=boxloc_expanded):
        tab_name = TAB_MAP[selected_display_tab]
        try:
            df = read_tab_cached(tab_name)
            if df.empty:
                st.info(f"No data found in tab: {tab_name}")
            else:
                show_df_view(
                    df,
                    key_cols=["StudyID", "Visit", "SampleID", "Memo"],
                    height_mobile=360,
                    height_desktop=520,
                    key_prefix="find_boxloc",
                )

                st.markdown("**StudyID → BoxNumber**")
                if "StudyID" not in df.columns:
                    st.info("This tab does not have a 'StudyID' column.")
                else:
                    studyids = df["StudyID"].dropna().astype(str).map(safe_strip)
                    options = sorted([s for s in studyids.unique().tolist() if s])
                    selected_studyid = st.selectbox("StudyID", ["(select)"] + options, key="find_studyid")
                    if selected_studyid != "(select)":
                        box_map = build_box_map()
                        box = box_map.get(safe_strip(selected_studyid).upper(), "")
                        if safe_strip(box) == "":
                            st.error("BoxNumber: Not Found")
                        else:
                            st.success(f"BoxNumber: {box}")
        except Exception as e:
            st.error("Box Location failed.")
            st.code(err_detail(e), language="text")

    # (rest of your FIND panels continue below…)
    st.info("Keep your existing LN Inventory Table / Freezer Search blocks here (unchanged).")

# ============================================================
# NOTE
# ============================================================
# I did NOT re-paste the rest of the file here because your request only changes
# the Find → Box Location expander rule.
#
# To apply this into your current full code:
# 1) Find your existing "with st.expander(... Box Location ...)" block in FIND
# 2) Replace just that expander header logic with the block above.
#
# If you still want me to paste the *entire* full code with this change applied,
# paste your latest full file (or tell me "use the last full code you sent"),
# and I will merge it cleanly without truncation.
